services:
  app:
    container_name: WebApp
    build:
      context: Frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

  api:
    container_name: API
    build:
      context: API
      dockerfile: Dockerfile
    ports:
      - "49501:8080"
    environment:
      - "ConnectionStrings:MySql=Server=SqlServer;Port=3306;Database=fnkvschedulerdb;Uid=api;Pwd=1234;SslMode=None;ConnectionReset=false;connect timeout=3600;AllowPublicKeyRetrieval=True"
  
  database:
    container_name: SqlServer
    build:
      context: Database
      dockerfile: Dockerfile
    ports:
      - "49301:3306"
    environment:
      MYSQL_DATABASE: fnkvschedulerdb
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - data:/var/lib/mysql

volumes:
  data: